/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const createElement: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number];
export const createLevel: (a: number, b: number, c: number) => [number, number, number];
export const deleteSelected: () => [number, number, number];
export const getScene: () => [number, number, number];
export const getSelected: () => [number, number, number];
export const initApp: () => [number, number];
export const listComponents: () => [number, number, number];
export const listElements: () => [number, number, number];
export const listProfiles: (a: number, b: number) => [number, number, number];
export const pickById: (a: number) => [number, number, number];
export const previewElement: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number, number];
export const previewProfile: (a: number, b: number, c: number, d: number) => [number, number, number];
export const registerComponent: (a: number, b: number) => [number, number, number];
export const registerProfile: (a: number, b: number) => [number, number, number];
export const selectElement: (a: number, b: number) => [number, number, number];
export const setActiveLevel: (a: number, b: number) => [number, number, number];
export const setElementPlacement: (a: number, b: number, c: number, d: number, e: number) => [number, number, number];
export const setLevelElevation: (a: number, b: number, c: number) => [number, number, number];
export const togglePickById: (a: number) => [number, number, number];
export const toggleSelectElement: (a: number, b: number) => [number, number, number];
export const updateElement: (a: number, b: number, c: number, d: number) => [number, number, number];
export const updateProfileType: (a: number, b: number, c: number, d: number) => [number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
